<?php
$page_title = 'Two-factor (2FA)';
$active_key = '2fa';
require __DIR__ . '/_layout.php';
require_once __DIR__ . '/../auth/totp.php';

$site = load_site_settings();
$issuer = ($site['name'] ?? 'WiFIBER') . ' Admin';

$enabled = !empty($user['totp_enabled']);
$error   = '';
$flash_codes = null;

/* If currently being set up (not yet enabled), keep the secret in the
 * session so the QR doesn't change between page loads. */
if (!$enabled && empty($_SESSION['totp_pending_secret'])) {
    $_SESSION['totp_pending_secret'] = totp_generate_secret();
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_csrf();
    $action = $_POST['action'] ?? '';

    if ($action === 'enable') {
        $secret = (string)($_SESSION['totp_pending_secret'] ?? '');
        $code   = trim((string)($_POST['code'] ?? ''));
        if (!totp_verify($secret, $code, 1)) {
            $error = 'That code didn\'t verify. Make sure your phone\'s clock is accurate and try again.';
        } else {
            $codes  = totp_recovery_codes(8);
            $hashes = totp_hash_recovery_codes($codes);
            update_user((int)$user['id'], function (array $u) use ($secret, $hashes) {
                $u['totp_secret']           = $secret;
                $u['totp_enabled']          = true;
                $u['totp_recovery_codes']   = $hashes;
                $u['totp_enabled_at']       = date('c');
                return $u;
            });
            unset($_SESSION['totp_pending_secret']);
            $flash_codes = $codes;
            $enabled = true;
            $user = find_user_by_id((int)$user['id']);
        }
    }

    if ($action === 'disable') {
        $pw = (string)($_POST['password'] ?? '');
        if (!password_verify($pw, $user['password_hash'] ?? '')) {
            $error = 'Wrong password.';
        } else {
            update_user((int)$user['id'], function (array $u) {
                $u['totp_secret']         = null;
                $u['totp_enabled']        = false;
                $u['totp_recovery_codes'] = [];
                return $u;
            });
            flash('success', 'Two-factor disabled.');
            header('Location: /admin/2fa.php');
            exit;
        }
    }

    if ($action === 'regen_codes' && $enabled) {
        $codes  = totp_recovery_codes(8);
        $hashes = totp_hash_recovery_codes($codes);
        update_user((int)$user['id'], function (array $u) use ($hashes) {
            $u['totp_recovery_codes'] = $hashes;
            return $u;
        });
        $flash_codes = $codes;
        $user = find_user_by_id((int)$user['id']);
    }
}
?>

<div class="portal-head">
  <h1>Two-factor authentication</h1>
  <p class="portal-sub">Add a second factor to your admin login. Use any TOTP app: Google Authenticator, Authy, 1Password, Microsoft Authenticator, Bitwarden, etc.</p>
</div>

<?php if ($error): ?>
  <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<?php if ($flash_codes): ?>
  <div class="portal-card" style="border-color:var(--accent);">
    <h2 style="color:var(--accent);">Save your recovery codes &mdash; right now</h2>
    <p>Each code lets you log in <strong>once</strong> if you lose your phone. <strong>This is the only time we'll show them.</strong> Print, screenshot, or paste into a password manager.</p>
    <div class="recovery-grid">
      <?php foreach ($flash_codes as $c): ?>
        <code><?= htmlspecialchars($c) ?></code>
      <?php endforeach; ?>
    </div>
    <p class="muted small" style="margin-top:14px;">Stored hashed. We can't recover them &mdash; only regenerate.</p>
  </div>
<?php endif; ?>

<?php if (!$enabled):
    $secret  = (string)$_SESSION['totp_pending_secret'];
    $account = $user['username'] . '@' . preg_replace('/^www\./', '', $_SERVER['HTTP_HOST'] ?? 'wifiber.co.za');
    $uri     = totp_uri($secret, $account, $issuer);
    $qr      = totp_qr_url($uri);
?>

  <div class="portal-card">
    <h2>1. Scan this QR with your authenticator app</h2>
    <div class="qr-row">
      <img src="<?= htmlspecialchars($qr, ENT_QUOTES) ?>" alt="2FA QR code" width="220" height="220" style="background:#fff;border-radius:8px;">
      <div>
        <p>Or enter this code manually:</p>
        <code class="big-code"><?= htmlspecialchars(totp_format_secret($secret)) ?></code>
        <p class="muted small">Account: <code><?= htmlspecialchars($account) ?></code><br>Issuer: <code><?= htmlspecialchars($issuer) ?></code></p>
        <p class="muted small">QR is generated by <a href="https://goqr.me" target="_blank" rel="noopener">api.qrserver.com</a> &mdash; if you'd rather not send the secret to a third party, use the manual code instead.</p>
      </div>
    </div>
  </div>

  <div class="portal-card">
    <h2>2. Enter the 6-digit code from your app to confirm</h2>
    <form method="post" class="form" autocomplete="off">
      <?= csrf_field() ?>
      <input type="hidden" name="action" value="enable">
      <div class="field">
        <input type="text" name="code" required inputmode="numeric" pattern="[0-9]{6}" maxlength="6"
               style="font-family:ui-monospace,'JetBrains Mono',monospace; letter-spacing:.3em; font-size:1.3rem; text-align:center;">
      </div>
      <button type="submit" class="btn btn-primary">Enable two-factor</button>
    </form>
  </div>

<?php else: ?>

  <div class="portal-card">
    <h2 style="color:var(--success);">2FA is enabled <?php if (!empty($user['totp_enabled_at'])): ?><span class="muted small" style="font-weight:400;">since <?= htmlspecialchars((string)$user['totp_enabled_at']) ?></span><?php endif; ?></h2>
    <p>You'll be asked for a code from your authenticator app (or a recovery code) every time you log in.</p>
    <p>Recovery codes left: <strong><?= count(array_filter((array)($user['totp_recovery_codes'] ?? []))) ?> / <?= count((array)($user['totp_recovery_codes'] ?? [])) ?></strong></p>

    <form method="post" class="inline-form" style="margin-top:14px;">
      <?= csrf_field() ?>
      <input type="hidden" name="action" value="regen_codes">
      <button type="submit" class="btn btn-ghost">Regenerate recovery codes</button>
    </form>
  </div>

  <div class="portal-card">
    <h2>Disable two-factor</h2>
    <p class="muted">Confirm with your password to turn 2FA off.</p>
    <form method="post" class="form">
      <?= csrf_field() ?>
      <input type="hidden" name="action" value="disable">
      <div class="field">
        <label>Your current password</label>
        <input type="password" name="password" required autocomplete="current-password">
      </div>
      <button type="submit" class="btn btn-danger">Disable 2FA</button>
    </form>
  </div>

<?php endif; ?>

<?php require __DIR__ . '/../auth/portal-footer.php'; ?>
